#!/bin/bash
#                 _     _ _                  
#   __ _ _ __ ___| |__ | (_)_ __  _   ___  __
#  / _` | '__/ __| '_ \| | | '_ \| | | \ \/ /
# | (_| | | | (__| | | | | | | | | |_| |>  < 
#  \__,_|_|  \___|_| |_|_|_|_| |_|\__,_/_/\_\
#  _           _        _ _       _   _                             _       _   
# (_)_ __  ___| |_ __ _| | | __ _| |_(_) ___  _ __    ___  ___ _ __(_)_ __ | |_ 
# | | '_ \/ __| __/ _` | | |/ _` | __| |/ _ \| '_ \  / __|/ __| '__| | '_ \| __|
# | | | | \__ \ || (_| | | | (_| | |_| | (_) | | | | \__ \ (__| |  | | |_) | |_ 
# |_|_| |_|___/\__\__,_|_|_|\__,_|\__|_|\___/|_| |_| |___/\___|_|  |_| .__/ \__|
#                                                                    |_|        
# Archlinux installation script for fully encrypted system using UEFI and NVMe
# Based on https://wiki.archlinux.org/index.php/Installation_guide
#
# 0. boot archlinux-date-x86_64.iso in UEFI mode
# 1. git clone https://github.com/johan-jansson/arch
# 2. ./arch

loadkeys sv-latin1
timedatectl set-ntp true

# generate gpt partition table
parted /dev/nvme1n1 mklabel gpt
parted /dev/nvme1n1 unit mib
parted /dev/nvme1n1 mkpart primary 1 512
parted /dev/nvme1n1 name 1 boot
parted /dev/nvme1n1 set 1 boot on
parted /dev/nvme1n1 mkpart primary 513 100%
parted /dev/nvme1n1 name 2 archlinux

# encrypt and open root partition /dev/mapper/crypt-root
cryptsetup luksFormat --verbose --key-size 512 --hash sha256 /dev/nvme1n1p2
cryptsetup open /dev/nvme1n1p2 arch

# initialize and mount new filesystems
mkfs.ext4 /dev/mapper/arch
mount /dev/mapper/arch /mnt
mkfs.fat -F32 /dev/nvme1n1p1
mkdir /mnt/boot
mount /dev/nvme1n1p1 /mnt/boot

# mount other filesystems which should be in the new /etc/fstab
cryptsetup open /dev/md/mercury:raid1 raid1
mkdir /mnt/home/
mkdir /mnt/home/data/
mount /dev/mapper/raid1 /mnt/home/data/
cryptsetup open /dev/sdb1 backup
mkdir /mnt/home/backup/
mount /dev/mapper/backup /mnt/home/backup/

# minimal environment with lan + wireless networking and wireguard VPN
pacstrap /mnt base efibootmgr grub linux linux-firmware mkinitcpio e2fsprogs mdadm iproute2 dhcpcd wpa_supplicant dialog wireguard-tools resolvconf sudo
genfstab -pU /mnt >> /mnt/etc/fstab
echo "tmpfs	/tmp	tmpfs	defaults,noatime,mode=1777	0	0" >> /mnt/etc/fstab
echo "raid1 /dev/md/raid1 none" >> /mnt/etc/crypttab
echo "backup /dev/sdb1 none" >> /mnt/etc/crypttab
arch-chroot /mnt ln -sf /usr/share/zoneinfo/Europe/Stockholm /etc/localtime
arch-chroot /mnt hwclock --systohc
echo "en_US.UTF-8 UTF-8" >> /mnt/etc/locale.gen
arch-chroot /mnt locale-gen
echo "LANG=en_US.UTF-8" > /mnt/etc/locale.conf
echo "KEYMAP=sv-latin1" > /mnt/etc/vconsole.conf
echo "mercury" > /mnt/etc/hostname
echo "127.0.0.1   localhost" >> /mnt/etc/hosts
echo "::1         localhost" >> /mnt/etc/hosts
echo "127.0.1.1   mercury.lind  mercury" >> /mnt/etc/hosts
arch-chroot /mnt systemctl enable dhcpcd
echo "%wheel ALL=(ALL) ALL" >> /mnt/etc/sudoers
arch-chroot /mnt useradd -m -g users -G wheel -s /bin/zsh johan
arch-chroot /mnt passwd johan
arch-chroot /mnt passwd -d root
arch-chroot /mnt sed -i 's/MODULES=()/MODULES=(ext4)/' /etc/mkinitcpio.conf
arch-chroot /mnt sed -i 's/HOOKS=(base\ udev\ autodetect\ modconf\ block\ filesystems\ keyboard\ fsck)/HOOKS=(base\ udev\ autodetect\ modconf\ block\ encrypt\ filesystems\ keyboard\ fsck)/' /etc/mkinitcpio.conf
arch-chroot /mnt mkinitcpio -p linux
arch-chroot /mnt grub-install --target=x86_64-efi --efi-directory=/boot
arch-chroot /mnt sed -i 's/GRUB_CMDLINE_LINUX=""/GRUB_CMDLINE_LINUX="cryptdevice=\/dev\/nvme1n1p2:arch"/' /etc/default/grub
arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg

# configure and enable wireguard VPN
cp /mnt/home/data/sync/integrity_vpn/*integrity_vpn.conf /mnt/etc/wireguard/
arch-chroot /mnt systemctl enable wg-quick@SEintegrity_vpn.service

# install basic tools
arch-chroot /mnt pacman --noconfirm -Sy git base-devel man-db neovim zsh zsh-syntax-highlighting

# minimal xorg with nvidia gpu acceleration and pulseaudio
arch-chroot /mnt pacman --noconfirm -Sy libx11 libxft xorg-server xorg-xinit xorg-xrandr xorg-xrdb xorg-xinput xclip xorg-setxkbmap nvidia nvidia-settings xorg-fonts-encodings libxinerama pulseaudio pulseaudio-alsa

# basic gnome
arch-chroot /mnt pacman --noconfirm -Sy gnome gnome-tweaks ffmpegthumbnailer tumbler gst-libav
arch-chroot /mnt systemctl enable NetworkManager
arch-chroot /mnt systemctl enable gdm

# basic system
arch-chroot /mnt pacman --noconfirm -Sy keepassxc thunderbird syncthing mpv transmission-gtk code inkscape gimp texstudio texlive-core obs-studio screenkey signal-desktop element-desktop 

# dependencies for vim workflows
arch-chroot /mnt pacman --noconfirm -Sy pdf2svg rtmpdump atomicparsley xdotool python-neovim python-pdftotext python-sympy nodejs yarn fzf ripgrep bat pacman-contrib

# deploy configuration management
arch-chroot /mnt mkdir /home/johan/.config/
arch-chroot /mnt mkdir /home/johan/.config/dot/
echo ".config/dot" >> /mnt/home/johan/.gitignore
arch-chroot /mnt git clone --bare https://github.com/johan-jansson/dot /home/johan/.config/dot
arch-chroot /mnt /usr/bin/git --git-dir=/home/johan/.config/dot/ --work-tree=/home/johan checkout
arch-chroot /mnt /usr/bin/git --git-dir=/home/johan/.config/dot/ --work-tree=/home/johan config --local status.showUntrackedFiles no
arch-chroot /mnt chown johan.users -R /home/johan/
arch-chroot /mnt chown johan.users /home/data/
arch-chroot /mnt chown johan.users /home/backup/
arch-chroot /mnt /usr/bin/git --git-dir=/home/johan/.config/dot/ --work-tree=/home/johan update-index --assume-unchanged "/home/johan/README.md"
arch-chroot /mnt rm -f "/home/johan/README.md"

# clean up and reboot
#umount -R /mnt
#reboot
