#!/bin/zsh

# deploy dotfiles and dotfile management
mkdir $HOME/.config/
mkdir $HOME/.config/dot/
echo ".config/dot" >> .gitignore # no recursion plz
git clone --bare https://github.com/johan-jansson/dot $HOME/.config/dot
/usr/bin/git --git-dir=$HOME/.config/dot/ --work-tree=$HOME checkout
/usr/bin/git --git-dir=$HOME/.config/dot/ --work-tree=$HOME config --local status.showUntrackedFiles no

# productivity
sudo pacman -Sy --noconfirm wireguard-tools keepassxc thunderbird syncthing code inkscape gimp texstudio texlive-core transmission-gtk obs-studio signal-desktop element-desktop vlc julia sxhkd

# dependencies for productivity, specific to configuration
sudo pacman --noconfirm -Sy openresolv pdf2svg screenkey rtmpdump atomicparsley xdotool python-neovim ttf-joypixels python-pdftotext python-sympy nodejs yarn fzf ripgrep bat pacman-contrib

# aur helper
cd $HOME
git clone https://aur.archlinux.org/yay
cd yay
makepkg -si --noconfirm
cd $HOME
rm -rf yay

# aur packages
yay --cleanafter -S brave-bin
yay --cleanafter -S ttf-juliamono
yay --cleanafter -S zoom
yay --cleanafter -S mattermost-desktop-bin
yay --cleanafter -S discord
yay --cleanafter -S teams
yay --cleanafter -S spotify

# cleanup
rm -f "$HOME/deploy"
rm -f "$HOME/README.md"
cd
config update-index --assume-unchanged "README.md"
